export const IS_USER_LOGGED = "IS_CUSTOMER_LOGGED";
export const USER_LOGOUT = "CUSTOMER_LOGOUT";
export const CHANGE_MOBILE_VIEW = "CHANGE_MOBILE_VIEW";
export const CHANGE_MOBILE = "CHANGE_MOBILE_NUMBER";
export const UPDATE_PROFILE = "UPDATE_PROFILE";
