export const IS_MERCHANT_LOGGED = "IS_MERCHANT_LOGGED";
export const IS_CUSTOMER_LOGGED = "IS_CUSTOMER_LOGGED";
export const MERCHANT_LOGOUT = "MERCHANT_LOGOUT";
export const CUSTOMER_LOGOUT = "CUSTOMER_LOGOUT";
